### ISSUE TITLE
support for gingerbread devices.

### ISSUE THREAD

**Issue by MF-Debug** [veeti/DisableFlagSecure#1]
can u plz include support for gibgerbread devices as well?

**Comment by veeti** [comment]
Gingerbread doesn't support screenshots in the first place, does it? What's the use case?

**Comment by MF-Debug** [comment]
in aosp it doesn't. but in samsung stock roms,it does! so i asked.

**Comment by veeti** [comment]
OK. I can't promise that it does anything, but I've uploaded a new version with support for 2.3.
