### ISSUE TITLE
Enable flag secure

### ISSUE THREAD

**Issue by shivamrathi99** [veeti/DisableFlagSecure#17]
Hi, installed your app named fi.veetipaananen.android.disableflagsecure_v3_c38d39.apk today, but i couldnt find it in the app section of my phone..

I just wanted to know how to uninstall the app and remove it from my phone.. or how to re enable flag secure
Thanks @veeti

**Comment by veeti** [comment]
You need a device with Xposed framework installed. You can uninstall from Settings -> Apps.
