### ISSUE TITLE
Google Play Movies & TV

### ISSUE THREAD

**Issue by benwalburn** [veeti/DisableFlagSecure#2]
This module doesn't work in the above mentioned app. I get a notification saying storage may be in use.

**Comment by veeti** [comment]
Try the new version.

**Comment by benwalburn** [comment]
New version allows screenshots, but the video in the screenshot is blank. You can see the progress bar and everything, but the video isn't there.

**Comment by veeti** [comment]
Works for me. What device and OS version are you using?

**Comment by benwalburn** [comment]
I'm using the OnePlus One, 4.4.4

**Comment by veeti** [comment]
Dunno, sorry.
