### ISSUE TITLE
Why do you suggest not leaving this on? 

### ISSUE THREAD

**Issue by monotony** [veeti/DisableFlagSecure#3]
Just curious...  My boyfriend installed a non xposed mod recently & completely  it jacked up his Bluetooth & certain other settings & he's having a hard time figuring out how to fix it. I totally trust xposed but I just want to be sure there's nothing risky that might happen if I download this mod :)

**Comment by veeti** [comment]
There are some legitimate reasons why you might want to keep the secure flag on in some apps. For example, [TextSecure](https://github.com/WhisperSystems/TextSecure) does it to prevent private conversations from showing up in the recent apps switcher. I could imagine banking apps, etc. doing the same.

If that doesn't matter to you, there shouldn't be any issues with leaving this module on permanently.
